# Generated by Django 4.2.7 on 2023-12-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_lodgings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('ID', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('N_Beds', models.IntegerField(max_length=10)),
                ('N_Bathrooms', models.IntegerField(max_length=5)),
                ('Capacitance_T', models.IntegerField()),
                ('type_lodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='type_lodgings.type_lodging')),
            ],
        ),
    ]
