# Generated by Django 4.2.2 on 2023-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='ID',
        ),
        migrations.AddField(
            model_name='lodging',
            name='image',
            field=models.ImageField(null=True, upload_to='lodgings_images'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='N_Bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='N_Beds',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='lodging',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
