# Generated by Django 4.2.2 on 2023-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0002_remove_lodging_id_lodging_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
