# Generated by Django 4.2.7 on 2024-01-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodgings', '0002_alter_lodging_image'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rlodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lodgings.lodging')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation')),
            ],
        ),
    ]
