# Generated by Django 4.2.7 on 2023-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ID', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
