# Generated by Django 4.2.7 on 2023-12-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
