# Generated by Django 5.0.1 on 2024-01-30 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumers', '0001_initial'),
        ('rstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterr', models.DateField()),
                ('datess', models.DateField()),
                ('dateff', models.DateField()),
                ('value', models.IntegerField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='costumers.costumer')),
                ('rstatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rstatus.rstatu')),
            ],
        ),
    ]
