# Generated by Django 5.0.1 on 2024-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_coder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rstatu',
            field=models.CharField(default='Reservado', max_length=200),
        ),
    ]
