# Generated by Django 5.0.1 on 2024-02-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_value_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='coder',
        ),
    ]
