# Generated by Django 4.2.7 on 2023-12-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserves', '0004_alter_reserve_costumer_alter_reserve_lodging'),
        ('services', '0002_service_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserves.reserve')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
        ),
    ]
