# Generated by Django 5.0.1 on 2024-01-28 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
