# Generated by Django 4.2.7 on 2023-12-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodgings', '0001_initial'),
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_I', models.DateField(max_length=30)),
                ('Status_R', models.CharField(max_length=255)),
                ('Pay_T', models.IntegerField()),
                ('Satisfaction', models.CharField(max_length=2000)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='costumers.costumer')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lodgings.lodging')),
            ],
        ),
    ]
