# Generated by Django 4.2.2 on 2023-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_alter_reserve_costumer_alter_reserve_lodging'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
