# Generated by Django 4.2.7 on 2023-12-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
        ('lodgings', '0003_lodging_status'),
        ('reserves', '0003_reserve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='costumers.costumer'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lodgings.lodging'),
        ),
    ]
