# Generated by Django 4.2.7 on 2023-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
