# Generated by Django 4.2.7 on 2024-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilitie_status'),
        ('facilities', '0002_remove_facilitie_document_facilitie_status'),
    ]

    operations = [
    ]
