# Generated by Django 4.2.2 on 2023-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=50, unique=True)),
                ('Document_type', models.CharField(max_length=20)),
                ('Document', models.IntegerField(max_length=20)),
            ],
        ),
    ]
