# Generated by Django 4.2.7 on 2023-12-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodgings', '0003_lodging_status'),
        ('facilities', '0002_remove_facilitie_document_facilitie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_Facilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('facilitie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facilitie')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lodgings.lodging')),
            ],
        ),
    ]
