# Generated by Django 5.0.1 on 2024-01-26 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typedocuments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('phone', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('typedocument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='typedocuments.typedocument')),
            ],
        ),
    ]
