# Generated by Django 5.0.1 on 2024-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlodgings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rlodging',
            old_name='value',
            new_name='price',
        ),
    ]
