# Generated by Django 4.2.7 on 2023-12-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_lodgings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_lodging',
            name='document',
        ),
        migrations.RemoveField(
            model_name='type_lodging',
            name='nationality',
        ),
    ]
