# Generated by Django 5.0.1 on 2024-02-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='typedocument',
        ),
    ]
